server:
  port: 9527

spring:
  profiles:
    active: dev
  data:
    redis:
      timeout: 30000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0

knife4j:
  gateway:
    tags-sorter: order
    strategy: manual

family-gateway:
  jwt:
    ignoreUrlSet:
      - /user/login
      - /user/register
      - /user/refresh
    authorization: Authorization
    accessKey: MTIzNDU2
    refresh-key: MTIzNDU2
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000